---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - kubernetes.core

  tasks:
    - name: Build operator image
      docker_image:
        build:
          path: '{{ project_dir }}'
          pull: no
        name: '{{ operator_image }}'
        tag: latest
        push: no
        source: build
        force_source: yes

    - name: Load image into kind cluster
      command: kind load docker-image --name osdk-test '{{ operator_image }}'
      register: result
      changed_when: '"not yet present" in result.stdout'

    - name: Create Namespace
      k8s:
        api_version: v1
        kind: Namespace
        name: '{{ namespace }}'

    - import_tasks: kustomize.yml
      vars:
        state: present
