---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: projects.ops.k8s.romanow
spec:
  group: ops.k8s.romanow
  names:
    kind: Project
    listKind: ProjectList
    plural: projects
    singular: project
    shortNames:
      - prj
  scope: Cluster
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Project is the Schema for the projects API
          type: object
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              type: object
              required: [ "members", "environments" ]
              properties:
                members:
                  type: array
                  items:
                    type: string
                environments:
                  type: array
                  items:
                    type: object
                    required: [ "name" ]
                    properties:
                      name:
                        type: string
                      resources:
                        type: object
                        properties:
                          requests:
                            type: object
                            properties:
                              cpu:
                                type: integer
                              memory:
                                type: string
                          limits:
                            type: object
                            properties:
                              cpu:
                                type: integer
                              memory:
                                type: string

      served: true
      storage: true
      subresources:
        status: {}